CREATE OR REPLACE PROCEDURE DELETE_activitycontent()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
     rows_deleted int;
     return_message string;
BEGIN
  CREATE or replace TEMPORARY TABLE temp_delete_activitycontent 
  as
  SELECT ID, OBJECT_NAME, RECORD_ID FROM IC_CRM.DELETE_TRACKER WHERE STATUS = 'open' and OBJECT_NAME = 'ActivityContent';

  CREATE or replace TEMPORARY TABLE temp_delete_oldvalue 
  as
  select a.*, 'DELETED' as Status from ACTIVITYCONTENT a 
  inner join temp_delete_activitycontent b
  on a.ACTIVITYID__C=b.RECORD_ID;

  update DELETE_TRACKER set STATUS = 'applied' where RECORD_ID in (select ACTIVITYID__C from temp_delete_oldvalue) and OBJECT_NAME = 'ActivityContent';

  select count(*) into rows_deleted from temp_delete_oldvalue;
  
  merge into ACTIVITYCONTENT a
  using temp_delete_activitycontent b
  on a.ACTIVITYID__C=b.RECORD_ID
  when matched
      then delete;

  merge into ACTIVITYCONTENT_FINAL a
  using temp_delete_activitycontent b
  on a.ACTIVITYID=b.RECORD_ID
  when matched
      then delete;
      
  INSERT into HISTORY_ACTIVITYCONTENT (ID, ACTIVITYID__C, SUBJECT__C, ASSOCIATED_FUND_S_NEW__C, ALL_FUND_DIVISIONS__C, EXTERNAL_CONTACTS__C, EXTERNAL_CONTACTS_EMAILS__C, EXTERNAL_CONTACTS_WITH_TITLE__C, INTERNAL_CONTACTS__C, ACTIVITY_TYPE__C, INTERNAL_CONTACT_EMAILS__C, CONTENT__C, "Owner.Name", AGENDA__C, KEY_TAKEAWAYS_RECAP__C, CATALYST__C, LASTMODIFIEDDATE, FOLLOW_UPS__C, PERSONAL__C, ACTIVITY_DATEONLY__C, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, MEETING_PURPOSE__C, BLUE_OWL_ACTIVE_INVESTMENT_TOTAL__C, ASSOCIATED_FUND_DIVISIONS__C, FUND_STRATEGY_IES__C, ACCOUNT_HQ_COUNTRY__C, ACTIVITY_RECORD_TYPE_NAME__C, STATUS)
  select b.ID, b.ACTIVITYID__C, b.SUBJECT__C, b.ASSOCIATED_FUND_S_NEW__C, b.ALL_FUND_DIVISIONS__C, b.EXTERNAL_CONTACTS__C, b.EXTERNAL_CONTACTS_EMAILS__C, b.EXTERNAL_CONTACTS_WITH_TITLE__C, b.INTERNAL_CONTACTS__C, b.ACTIVITY_TYPE__C, b.INTERNAL_CONTACT_EMAILS__C, b.CONTENT__C, b."Owner.Name", b.AGENDA__C, b.KEY_TAKEAWAYS_RECAP__C, b.CATALYST__C, b.LASTMODIFIEDDATE, b.FOLLOW_UPS__C, b.PERSONAL__C, b.ACTIVITY_DATEONLY__C, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, TO_TIMESTAMP(b.LASTMODIFIEDDATE)), b.HASH_DATA, b.MEETING_PURPOSE__C, b.BLUE_OWL_ACTIVE_INVESTMENT_TOTAL__C, b.ASSOCIATED_FUND_DIVISIONS__C, b.FUND_STRATEGY_IES__C, b.ACCOUNT_HQ_COUNTRY__C, b.ACTIVITY_RECORD_TYPE_NAME__C, b.Status from temp_delete_oldvalue b;

  INSERT into HISTORY_ACTIVITYCONTENT_FINAL (ID, ACTIVITYID, SUBJECT, FUNDS, FUNDDIVISIONS, EXTERNALCONTACTS, EXTERNALCONTACTEMAILS, EXTERNALCONTACTTITLE, INTERNALCONTACTS, ACTIVITYTYPE, INTERNALCONTACTEMAILS, NOTES, OWNERNAME, AGENDA, KEYTAKEAWAYSRECAP, CATALYST, LASTMODIFIEDDATE, FOLLOWUPS, PERSONAL, ACTIVITYDATEONLY, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, MEETINGPURPOSE, BLUEOWLACTIVEINVESTMENTTOTAL, ASSOCIATEDFUNDDIVISIONS, "Fund Strategy(ies)", ACCOUNTHQCOUNTRY, ACTIVITYRECORDTYPENAME, STATUS)
  select b.ID, b.ACTIVITYID__C, b.SUBJECT__C, b.ASSOCIATED_FUND_S_NEW__C, b.ALL_FUND_DIVISIONS__C, b.EXTERNAL_CONTACTS__C, b.EXTERNAL_CONTACTS_EMAILS__C, b.EXTERNAL_CONTACTS_WITH_TITLE__C, b.INTERNAL_CONTACTS__C, b.ACTIVITY_TYPE__C, b.INTERNAL_CONTACT_EMAILS__C, b.CONTENT__C, b."Owner.Name", b.AGENDA__C, b.KEY_TAKEAWAYS_RECAP__C, b.CATALYST__C, b.LASTMODIFIEDDATE, b.FOLLOW_UPS__C, b.PERSONAL__C, b.ACTIVITY_DATEONLY__C, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, TO_TIMESTAMP(b.LASTMODIFIEDDATE)), b.HASH_DATA, b.MEETING_PURPOSE__C, b.BLUE_OWL_ACTIVE_INVESTMENT_TOTAL__C, b.ASSOCIATED_FUND_DIVISIONS__C, b.FUND_STRATEGY_IES__C, b.ACCOUNT_HQ_COUNTRY__C, b.ACTIVITY_RECORD_TYPE_NAME__C, b.Status from temp_delete_oldvalue b;
  
   return_message := 'SUCCESS' || ',' || to_varchar(rows_deleted);
  
  RETURN :return_message;
  EXCEPTION
          WHEN STATEMENT_ERROR THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
          WHEN OTHER THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
END;
$$;

