CREATE OR REPLACE PROCEDURE DELETE_fund()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
     rows_deleted int;
     return_message string;
BEGIN
  CREATE or replace TEMPORARY TABLE temp_delete_fund 
  as
  SELECT ID, OBJECT_NAME, RECORD_ID FROM IC_CRM.DELETE_TRACKER WHERE STATUS = 'open' and OBJECT_NAME = 'Fund';

  CREATE or replace TEMPORARY TABLE temp_delete_oldvalue 
  as
  select a.*, 'DELETED' as Status from FUND a 
  inner join temp_delete_fund b
  on a.X18_DIGIT_FUND_ID__C=b.RECORD_ID;

  update DELETE_TRACKER set STATUS = 'applied' where RECORD_ID in (select X18_DIGIT_FUND_ID__C from temp_delete_oldvalue) and OBJECT_NAME = 'Fund';

  select count(*) into rows_deleted from temp_delete_oldvalue;
  
  merge into FUND a
  using temp_delete_fund b
  on a.X18_DIGIT_FUND_ID__C=b.RECORD_ID
  when matched
      then delete;

  merge into FUND_FINAL a
  using temp_delete_fund b
  on a.X18_DIGIT_FUND_ID=b.RECORD_ID
  when matched
      then delete;
      
  INSERT into HISTORY_FUND (X18_DIGIT_FUND_ID__C, DIVISION__C, STRATEGY__C, NAME, FUND_LEGAL_NAME__C, IN_MARKET__C, SUB_STRATEGY__C, FUND_TYPE_NAME__C, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, STATUS, LASTMODIFIEDDATE, BO_FUND_CLASSIFICATION__C, X2025_INST_TARGET__C, X2025_INST_TARGET_NANORTHEAST__C, X2025_INST_TARGET_NAWESTCOAST__C, X2025_INST_TARGET_EUROPE__C, X2025_MIDDLE_EAST_IBD_TARGET__C, X2025_INST_TARGET_ASIA__C, X2025_AUSTRALASIA_IBD_TARGET__C, X2025_INST_TARGET_INSURANCE__C, X2025_INSTITUTIONAL_TARGET_LIQUID_CREDIT__C)
  select b.X18_DIGIT_FUND_ID__C, b.DIVISION__C, b.STRATEGY__C, b.NAME, b.FUND_LEGAL_NAME__C, b.IN_MARKET__C, b.SUB_STRATEGY__C, b.FUND_TYPE_NAME__C, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, TO_TIMESTAMP(b.LASTMODIFIEDDATE)), b.HASH_DATA, b.Status, b.LASTMODIFIEDDATE, b.BO_FUND_CLASSIFICATION__C, b.X2025_INST_TARGET__C, b.X2025_INST_TARGET_NANORTHEAST__C, b.X2025_INST_TARGET_NAWESTCOAST__C, b.X2025_INST_TARGET_EUROPE__C, b.X2025_MIDDLE_EAST_IBD_TARGET__C, b.X2025_INST_TARGET_ASIA__C, b.X2025_AUSTRALASIA_IBD_TARGET__C, b.X2025_INST_TARGET_INSURANCE__C, b.X2025_INSTITUTIONAL_TARGET_LIQUID_CREDIT__C from temp_delete_oldvalue b;

  INSERT into HISTORY_FUND_FINAL (X18_DIGIT_FUND_ID, PLATFORM, STRATEGY, FUNDSHORTENEDNAME, FUNDLEGALNAME, INMARKET, SUBSTRATEGY, FUNDTYPENAME, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, STATUS, LASTMODIFIEDDATE, "BOFundClassification", "2025IcTarget", "2025NAEastIcTarget", "2025WestIcTarget", "2025EuropeICTarget", "2025MiddleEastICTarget", "2025AsiaICTarget", "2025AustraliaICTarget", "2025InsuranceICTarget", "2025LiquidCreditICTarget")
  select b.X18_DIGIT_FUND_ID__C, b.DIVISION__C, b.STRATEGY__C, b.NAME, b.FUND_LEGAL_NAME__C, b.IN_MARKET__C, b.SUB_STRATEGY__C, b.FUND_TYPE_NAME__C, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, TO_TIMESTAMP(b.LASTMODIFIEDDATE)), b.HASH_DATA, b.Status, b.LASTMODIFIEDDATE, b.BO_FUND_CLASSIFICATION__C, b.X2025_INST_TARGET__C, b.X2025_INST_TARGET_NANORTHEAST__C, b.X2025_INST_TARGET_NAWESTCOAST__C, b.X2025_INST_TARGET_EUROPE__C, b.X2025_MIDDLE_EAST_IBD_TARGET__C, b.X2025_INST_TARGET_ASIA__C, b.X2025_AUSTRALASIA_IBD_TARGET__C, b.X2025_INST_TARGET_INSURANCE__C, b.X2025_INSTITUTIONAL_TARGET_LIQUID_CREDIT__C from temp_delete_oldvalue b;
  
   return_message := 'SUCCESS' || ',' || to_varchar(rows_deleted);
  
  RETURN :return_message;
  EXCEPTION
          WHEN STATEMENT_ERROR THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
          WHEN OTHER THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
END;
$$;

