-- Select database and schema
USE DATABASE IC_CRM_DB;
USE SCHEMA IC_CRM;

-- Get DDL for all tables
SELECT 
    'ACCOUNT' as TABLE_NAME,
    GET_DDL('TABLE', 'ACCOUNT') as DDL
UNION ALL
SELECT 
    'ACTIVITYCONTENT' as TABLE_NAME,
    GET_DDL('TABLE', 'ACTIVITYCONTENT') as DDL
UNION ALL
SELECT 
    'CONTACT' as TABLE_NAME,
    GET_DDL('TABLE', 'CONTACT') as DDL
UNION ALL
SELECT 
    'EVENT' as TABLE_NAME,
    GET_DDL('TABLE', 'EVENT') as DDL
UNION ALL
SELECT 
    'FUND' as TABLE_NAME,
    GET_DDL('TABLE', 'FUND') as DDL
UNION ALL
SELECT 
    'INVESTMENT' as TABLE_NAME,
    GET_DDL('TABLE', 'INVESTMENT') as DDL
UNION ALL
SELECT 
    'LEGALENTITY' as TABLE_NAME,
    GET_DDL('TABLE', 'LEGALENTITY') as DDL
UNION ALL
SELECT 
    'LPCONRELATIONSHIP' as TABLE_NAME,
    GET_DDL('TABLE', 'LPCONRELATIONSHIP') as DDL
UNION ALL
SELECT 
    'OPPORTUNITY' as TABLE_NAME,
    GET_DDL('TABLE', 'OPPORTUNITY') as DDL
UNION ALL
SELECT 
    'TASK' as TABLE_NAME,
    GET_DDL('TABLE', 'TASK') as DDL
-- Final tables
UNION ALL
SELECT 
    'ACCOUNT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'ACCOUNT_FINAL') as DDL
UNION ALL
SELECT 
    'ACTIVITYCONTENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'ACTIVITYCONTENT_FINAL') as DDL
UNION ALL
SELECT 
    'CONTACT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'CONTACT_FINAL') as DDL
UNION ALL
SELECT 
    'EVENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'EVENT_FINAL') as DDL
UNION ALL
SELECT 
    'FUND_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'FUND_FINAL') as DDL
UNION ALL
SELECT 
    'INVESTMENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'INVESTMENT_FINAL') as DDL
UNION ALL
SELECT 
    'LEGALENTITY_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'LEGALENTITY_FINAL') as DDL
UNION ALL
SELECT 
    'LPCONRELATIONSHIP_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'LPCONRELATIONSHIP_FINAL') as DDL
UNION ALL
SELECT 
    'OPPORTUNITY_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'OPPORTUNITY_FINAL') as DDL
UNION ALL
SELECT 
    'TASK_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'TASK_FINAL') as DDL
-- History tables
UNION ALL
SELECT 
    'HISTORY_ACCOUNT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACCOUNT') as DDL
UNION ALL
SELECT 
    'HISTORY_ACTIVITYCONTENT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACTIVITYCONTENT') as DDL
UNION ALL
SELECT 
    'HISTORY_CONTACT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_CONTACT') as DDL
UNION ALL
SELECT 
    'HISTORY_EVENT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_EVENT') as DDL
UNION ALL
SELECT 
    'HISTORY_FUND' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_FUND') as DDL
UNION ALL
SELECT 
    'HISTORY_INVESTMENT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_INVESTMENT') as DDL
UNION ALL
SELECT 
    'HISTORY_LEGALENTITY' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LEGALENTITY') as DDL
UNION ALL
SELECT 
    'HISTORY_LPCONRELATIONSHIP' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LPCONRELATIONSHIP') as DDL
UNION ALL
SELECT 
    'HISTORY_OPPORTUNITY' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_OPPORTUNITY') as DDL
UNION ALL
SELECT 
    'HISTORY_TASK' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_TASK') as DDL
-- History Final tables
UNION ALL
SELECT 
    'HISTORY_ACCOUNT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACCOUNT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_ACTIVITYCONTENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACTIVITYCONTENT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_CONTACT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_CONTACT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_EVENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_EVENT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_FUND_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_FUND_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_INVESTMENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_INVESTMENT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_LEGALENTITY_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LEGALENTITY_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_LPCONRELATIONSHIP_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LPCONRELATIONSHIP_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_OPPORTUNITY_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_OPPORTUNITY_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_TASK_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_TASK_FINAL') as DDL;

