-- Select database and schema
USE DATABASE IC_CRM_DB;
USE SCHEMA IC_CRM;

-- Get DDL for all tables
SELECT 
    'Account' as TABLE_NAME,
    GET_DDL('TABLE', 'Account') as DDL
UNION ALL
SELECT 
    'ActivityContent' as TABLE_NAME,
    GET_DDL('TABLE', 'ActivityContent') as DDL
UNION ALL
SELECT 
    'Contact' as TABLE_NAME,
    GET_DDL('TABLE', 'Contact') as DDL
UNION ALL
SELECT 
    'Event' as TABLE_NAME,
    GET_DDL('TABLE', 'Event') as DDL
UNION ALL
SELECT 
    'Fund' as TABLE_NAME,
    GET_DDL('TABLE', 'Fund') as DDL
UNION ALL
SELECT 
    'Investment' as TABLE_NAME,
    GET_DDL('TABLE', 'Investment') as DDL
UNION ALL
SELECT 
    'LegalEntity' as TABLE_NAME,
    GET_DDL('TABLE', 'LegalEntity') as DDL
UNION ALL
SELECT 
    'LP_Consultant_Relationship' as TABLE_NAME,
    GET_DDL('TABLE', 'LP_Consultant_Relationship') as DDL
UNION ALL
SELECT 
    'Opportunity' as TABLE_NAME,
    GET_DDL('TABLE', 'Opportunity') as DDL
UNION ALL
SELECT 
    'Task' as TABLE_NAME,
    GET_DDL('TABLE', 'Task') as DDL
-- Final tables
UNION ALL
SELECT 
    'Account_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Account_final') as DDL
UNION ALL
SELECT 
    'ActivityContent_final' as TABLE_NAME,
    GET_DDL('TABLE', 'ActivityContent_final') as DDL
UNION ALL
SELECT 
    'Contact_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Contact_final') as DDL
UNION ALL
SELECT 
    'Event_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Event_final') as DDL
UNION ALL
SELECT 
    'Fund_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Fund_final') as DDL
UNION ALL
SELECT 
    'Investment_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Investment_final') as DDL
UNION ALL
SELECT 
    'LegalEntity_final' as TABLE_NAME,
    GET_DDL('TABLE', 'LegalEntity_final') as DDL
UNION ALL
SELECT 
    'LP_Consultant_Relationship_final' as TABLE_NAME,
    GET_DDL('TABLE', 'LP_Consultant_Relationship_final') as DDL
UNION ALL
SELECT 
    'Opportunity_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Opportunity_final') as DDL
UNION ALL
SELECT 
    'Task_final' as TABLE_NAME,
    GET_DDL('TABLE', 'Task_final') as DDL
-- History tables
UNION ALL
SELECT 
    'HISTORY_ACCOUNT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACCOUNT') as DDL
UNION ALL
SELECT 
    'HISTORY_ACTIVITYCONTENT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACTIVITYCONTENT') as DDL
UNION ALL
SELECT 
    'HISTORY_CONTACT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_CONTACT') as DDL
UNION ALL
SELECT 
    'HISTORY_EVENT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_EVENT') as DDL
UNION ALL
SELECT 
    'HISTORY_FUND' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_FUND') as DDL
UNION ALL
SELECT 
    'HISTORY_INVESTMENT' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_INVESTMENT') as DDL
UNION ALL
SELECT 
    'HISTORY_LEGALENTITY' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LEGALENTITY') as DDL
UNION ALL
SELECT 
    'HISTORY_LP_CONSULTANT_RELATIONSHIP' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LP_CONSULTANT_RELATIONSHIP') as DDL
UNION ALL
SELECT 
    'HISTORY_OPPORTUNITY' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_OPPORTUNITY') as DDL
UNION ALL
SELECT 
    'HISTORY_TASK' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_TASK') as DDL
-- History Final tables
UNION ALL
SELECT 
    'HISTORY_ACCOUNT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACCOUNT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_ACTIVITYCONTENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_ACTIVITYCONTENT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_CONTACT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_CONTACT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_EVENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_EVENT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_FUND_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_FUND_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_INVESTMENT_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_INVESTMENT_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_LEGALENTITY_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LEGALENTITY_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_LP_CONSULTANT_RELATIONSHIP_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_LP_CONSULTANT_RELATIONSHIP_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_OPPORTUNITY_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_OPPORTUNITY_FINAL') as DDL
UNION ALL
SELECT 
    'HISTORY_TASK_FINAL' as TABLE_NAME,
    GET_DDL('TABLE', 'HISTORY_TASK_FINAL') as DDL;

