CREATE OR REPLACE PROCEDURE DELETE_investment()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
     rows_deleted int;
     return_message string;
BEGIN
  CREATE or replace TEMPORARY TABLE temp_delete_investment 
  as
  SELECT ID, OBJECT_NAME, RECORD_ID FROM IC_CRM.DELETE_TRACKER WHERE STATUS = 'open' and OBJECT_NAME = 'Investment';

  CREATE or replace TEMPORARY TABLE temp_delete_oldvalue 
  as
  select a.*, 'DELETED' as Status from INVESTMENT a 
  inner join temp_delete_investment b
  on a.X18_DIGIT_INVESTMENT_ID__C=b.RECORD_ID;

  update DELETE_TRACKER set STATUS = 'applied' where RECORD_ID in (select X18_DIGIT_INVESTMENT_ID__C from temp_delete_oldvalue) and OBJECT_NAME = 'Investment';

  select count(*) into rows_deleted from temp_delete_oldvalue;
  
  merge into INVESTMENT a
  using temp_delete_investment b
  on a.X18_DIGIT_INVESTMENT_ID__C=b.RECORD_ID
  when matched
      then delete;

  merge into INVESTMENT_FINAL a
  using temp_delete_investment b
  on a.INVESTMENTID=b.RECORD_ID
  when matched
      then delete;
      
  INSERT into HISTORY_INVESTMENT (X18_DIGIT_INVESTMENT_ID__C, FUND__C, FEEDER_FUND__C, DIVISION__C, DIVISION_STRATEGY__C, FUND_TYPE__C, COMMITMENT_AMOUNT__C, ACTIVE_INVESTMENT_AMOUNT__C, ORIGINAL_INVESTMENT_DATE__C, ID, X18_DIGIT_FUND_ID__C, CONSULTANT_INFLUENCING_INVESTMENT__C, LASTMODIFIEDDATE, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, STATUS, FUND_NAME__C, FUND_STRATEGY__C, INVESTMENT_TYPE__C, INVESTMENT_NAME__C, TOTAL_TRANSFERRED_AWAY__C, TOTAL_TRANSFERRED_TO__C, LEGAL_ENTITY__C)
  select b.X18_DIGIT_INVESTMENT_ID__C, b.FUND__C, b.FEEDER_FUND__C, b.DIVISION__C, b.DIVISION_STRATEGY__C, b.FUND_TYPE__C, b.COMMITMENT_AMOUNT__C, b.ACTIVE_INVESTMENT_AMOUNT__C, b.ORIGINAL_INVESTMENT_DATE__C, b.ID, b.X18_DIGIT_FUND_ID__C, b.CONSULTANT_INFLUENCING_INVESTMENT__C, b.LASTMODIFIEDDATE, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, TO_TIMESTAMP(b.LASTMODIFIEDDATE)), b.HASH_DATA, b.Status, b.FUND_NAME__C, b.FUND_STRATEGY__C, b.INVESTMENT_TYPE__C, b.INVESTMENT_NAME__C, b.TOTAL_TRANSFERRED_AWAY__C, b.TOTAL_TRANSFERRED_TO__C, b.LEGAL_ENTITY__C from temp_delete_oldvalue b;

  INSERT into HISTORY_INVESTMENT_FINAL (INVESTMENTID, FUND, SUBFUND, DIVISION, DIVISIONSTRATEGY, FUNDTYPE, ORIGINALCOMMITMENTAMOUNT, ACTIVEINVESTMENTAMOUNT, INVESTMENTDATE, ACCOUNTID, FUNDID, INFLUENCINGCONSULTANTACCOUNT, LASTMODIFIEDDATE, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, STATUS, FUNDNAME, FUNDSTRATEGY, INVESTMENTTYPE, INVESTMENTNAME, TOTALTRANSFEREDAWAY, TOTALTRANSFEREDIN, LEGALENTITY)
  select b.X18_DIGIT_INVESTMENT_ID__C, b.FUND__C, b.FEEDER_FUND__C, b.DIVISION__C, b.DIVISION_STRATEGY__C, b.FUND_TYPE__C, b.COMMITMENT_AMOUNT__C, b.ACTIVE_INVESTMENT_AMOUNT__C, b.ORIGINAL_INVESTMENT_DATE__C, b.ID, b.X18_DIGIT_FUND_ID__C, b.CONSULTANT_INFLUENCING_INVESTMENT__C, b.LASTMODIFIEDDATE, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, TO_TIMESTAMP(b.LASTMODIFIEDDATE)), b.HASH_DATA, b.Status, b.FUND_NAME__C, b.FUND_STRATEGY__C, b.INVESTMENT_TYPE__C, b.INVESTMENT_NAME__C, b.TOTAL_TRANSFERRED_AWAY__C, b.TOTAL_TRANSFERRED_TO__C, b.LEGAL_ENTITY__C from temp_delete_oldvalue b;
  
   return_message := 'SUCCESS' || ',' || to_varchar(rows_deleted);
  
  RETURN :return_message;
  EXCEPTION
          WHEN STATEMENT_ERROR THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
          WHEN OTHER THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
END;
$$;

