CREATE OR REPLACE PROCEDURE DELETE_opportunity()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
     rows_deleted int;
     return_message string;
BEGIN
  CREATE or replace TEMPORARY TABLE temp_delete_opportunity 
  as
  SELECT ID, OBJECT_NAME, RECORD_ID FROM IC_CRM.DELETE_TRACKER WHERE STATUS = 'open' and OBJECT_NAME = 'Opportunity';

  CREATE or replace TEMPORARY TABLE temp_delete_oldvalue 
  as
  select a.*, 'DELETED' as Status from OPPORTUNITY a 
  inner join temp_delete_opportunity b
  on a.id=b.RECORD_ID;

  update DELETE_TRACKER set STATUS = 'applied' where RECORD_ID in (select id from temp_delete_oldvalue) and OBJECT_NAME = 'Opportunity';

  select count(*) into rows_deleted from temp_delete_oldvalue;
  
  merge into OPPORTUNITY a
  using temp_delete_opportunity b
  on a.id=b.RECORD_ID
  when matched
      then delete;

  merge into OPPORTUNITY_FINAL a
  using temp_delete_opportunity b
  on a.OPPORTUNITYID=b.RECORD_ID
  when matched
      then delete;
      
  INSERT into HISTORY_OPPORTUNITY (ID, ACCOUNTID, OWNER_NAME_TEXT__C, PLATFORM_STRATEGY__C, NAME, FUND_DIVISON__C, STRATEGY__C, FUND_NAME__C, BO_FUND_CLASSIFICATION__C, STAGENAME, AMOUNT, EXPECTEDREVENUE, PROBABILITY, CLOSEDATE, FISCAL, INFLUENCING_CONSULTANT__C, BLUE_OWL_INVESTOR_STATUS__C, POD__C, COVERAGE_REGION__C, GEOGRAPHIC_REGION__C, NEXTSTEP, CREATEDDATE, LASTMODIFIEDDATE, X18_DIGIT_OPPORTUNITY_ID__C, OWNERID, FUND_ID__C, INVESTMENT_TARGET__C, IBD_STRATEGIC_ACCOUNT__C, DAYS_SINCE_LAST_ACTIVITY__C, STAGE_DURATION__C, OPPORTUNITY_RECORD_TYPE_NAME__C, DIVISION__C, CONTACTID__C, HQ_COUNTRY__C, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, STATUS, INVESTMENT_AMOUNT_MM__C, OPPORTUNITY_STATUS__C, STATUS_NEXT_STEPS__C)
  select b.ID, b.ACCOUNTID, b.OWNER_NAME_TEXT__C, b.PLATFORM_STRATEGY__C, b.NAME, b.FUND_DIVISON__C, b.STRATEGY__C, b.FUND_NAME__C, b.BO_FUND_CLASSIFICATION__C, b.STAGENAME, b.AMOUNT, b.EXPECTEDREVENUE, b.PROBABILITY, b.CLOSEDATE, b.FISCAL, b.INFLUENCING_CONSULTANT__C, b.BLUE_OWL_INVESTOR_STATUS__C, b.POD__C, b.COVERAGE_REGION__C, b.GEOGRAPHIC_REGION__C, b.NEXTSTEP, b.CREATEDDATE, b.LASTMODIFIEDDATE, b.X18_DIGIT_OPPORTUNITY_ID__C, b.OWNERID, b.FUND_ID__C, b.INVESTMENT_TARGET__C, b.IBD_STRATEGIC_ACCOUNT__C, b.DAYS_SINCE_LAST_ACTIVITY__C, b.STAGE_DURATION__C, b.OPPORTUNITY_RECORD_TYPE_NAME__C, b.DIVISION__C, b.CONTACTID__C, b.HQ_COUNTRY__C, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, b.LASTMODIFIEDDATE), b.HASH_DATA, b.Status, b.INVESTMENT_AMOUNT_MM__C, b.OPPORTUNITY_STATUS__C, b.STATUS_NEXT_STEPS__C from temp_delete_oldvalue b;

  INSERT into HISTORY_OPPORTUNITY_FINAL (OPPORTUNITYID, ACCOUNTID, "OwnerName(Text)", "PLATFORM+STRATEGY", OPPORTUNITYNAME, FUNDDIVISON, STRATEGY, FUNDNAME, BOFUNDCLASSIFICATION, STAGE, INVESTMENTAMOUNT, EXPECTEDREVENUE, PROBABILITYPERCENTAGE, CLOSEDATE, FISCALPERIOD, INFLUENCINGCONSULTANTACCOUNT, BLUEOWLINVESTORSTATUS, ICPOD, COVERAGEREGION, GEOGRAPHICREGION, NEXTSTEP, CREATEDDATE, LASTMODIFIEDDATE, X18_DIGIT_OPPORTUNITY_ID, OPPORTUNITYOWNER, FUNDID, INVESTMENTTARGET, ICSTRATEGICACCOUNT, DAYSSINCELASTACTIVITY, STAGEDURATION, OPPORTUNITYRECORDTYPENAME, DIVISION, CONTACTID, HQCOUNTRY, EFFECTIVE_FROM, EFFECTIVE_TO, HASH_DATA, STATUS, "InvestmentAmount(mm)", OPPORTUNITYSTATUS, STATUSNEXTSTEPS)
  select b.ID, b.ACCOUNTID, b.OWNER_NAME_TEXT__C, b.PLATFORM_STRATEGY__C, b.NAME, b.FUND_DIVISON__C, b.STRATEGY__C, b.FUND_NAME__C, b.BO_FUND_CLASSIFICATION__C, b.STAGENAME, b.AMOUNT, b.EXPECTEDREVENUE, b.PROBABILITY, b.CLOSEDATE, b.FISCAL, b.INFLUENCING_CONSULTANT__C, b.BLUE_OWL_INVESTOR_STATUS__C, b.POD__C, b.COVERAGE_REGION__C, b.GEOGRAPHIC_REGION__C, b.NEXTSTEP, b.CREATEDDATE, b.LASTMODIFIEDDATE, b.X18_DIGIT_OPPORTUNITY_ID__C, b.OWNERID, b.FUND_ID__C, b.INVESTMENT_TARGET__C, b.IBD_STRATEGIC_ACCOUNT__C, b.DAYS_SINCE_LAST_ACTIVITY__C, b.STAGE_DURATION__C, b.OPPORTUNITY_RECORD_TYPE_NAME__C, b.DIVISION__C, b.CONTACTID__C, b.HQ_COUNTRY__C, b.EFFECTIVE_FROM, DATEADD(SECOND, -1, b.LASTMODIFIEDDATE), b.HASH_DATA, b.Status, b.INVESTMENT_AMOUNT_MM__C, b.OPPORTUNITY_STATUS__C, b.STATUS_NEXT_STEPS__C from temp_delete_oldvalue b;
  
   return_message := 'SUCCESS' || ',' || to_varchar(rows_deleted);
  
  RETURN :return_message;
  EXCEPTION
          WHEN STATEMENT_ERROR THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
          WHEN OTHER THEN
            return_message := OBJECT_CONSTRUCT(
              'Error Type', 'STATEMENT_ERROR',
              'SQLCODE', SQLCODE,
              'SQLERRM', SQLERRM,
              'SQLSTATE', SQLSTATE
            );
            ROLLBACK;
            RETURN :return_message;
END;
$$;

